<?php

use Hypermage\BlockCustomerHeader\ViewModel\Header as HeaderViewModel;
use Hypermage\Core\ViewModel\Htmx as HtmxViewModel;
use Magento\Framework\Escaper;
use Magento\Theme\Block\Html\Header;

/** @var Header $block */
/** @var Escaper $escaper */

/** @var HtmxViewModel $htmViewModel */
$htmViewModel = $block->getData('htmx_view_model');
$isHtmxRequest = $htmViewModel->isHtmxRequest();

/** @var HeaderViewModel $headerViewModel */
$headerViewModel = $block->getData('header_view_model');

$customer = $isHtmxRequest ? $headerViewModel->getCustomerData() : null;
$hxTrigger = $isHtmxRequest ? 'none' : 'revealed';
$welcomeMessage = $block->getWelcome();

$hxUrl = $htmViewModel->getUrl('/hypermage/block/block', [
    'block_specification' => $htmViewModel->getBlockSpecification($block)->toArray(),
]);
?>

<?php if ($block->getShowPart() == 'welcome'): ?>
    <li class="greet welcome"
        hx-trigger="<?= $hxTrigger ?>"
        hx-get="<?= $hxUrl ?>"
        hx-swap="outerHTML"
    >
        <?php if ($customer?->getId()): ?>
            <span class="logged-in">
                <?= $escaper->escapeHtml(__('Welcome, %1!', $customer->getName())) ?>
            </span>
        <?php else: ?>
            <span class="not-logged-in">
                <?= $escaper->escapeHtml($welcomeMessage) ?>
            </span>
            <?= $block->getBlockHtml('header.additional') ?>
        <?php endif; ?>
    </li>
<?php elseif ($block->getShowPart() == 'other'): ?>
    <?= $block->getChildHtml() ?>
<?php endif ?>
