<?php

use Hypermage\BlockCustomerHeader\ViewModel\Header as ViewModelHeader;
use Hypermage\Core\ViewModel\Htmx;
use Magento\Framework\Escaper;
use Magento\Theme\Block\Html\Header;

/** @var Header $block */
/** @var Escaper $escaper */

/** @var ViewModelHeader $viewModel */
$viewModel = $block->getViewModel();

/** @var Htmx $htmx */
$htmx = $block->getHtmx();
$isHtmxRequest = $htmx->isHtmxRequest();

$customer = $isHtmxRequest ? $viewModel->getCustomerData() : null;
$hxTrigger = $isHtmxRequest ? null : 'revealed';
$welcomeMessage = $block->getWelcome();

$hxUrl = $htmx->getUrl('/hypermage/block/block', [
    'block_specification' => $htmx->getBlockSpecification($block)->toArray(),
]);
?>

<?php if ($block->getShowPart() == 'welcome'): ?>
    <li class="greet welcome"
        hx-get="<?= $hxUrl ?>"
        hx-trigger="<?= $hxTrigger ?>"
        hx-swap="outerHTML"
    >
        <?php if ($customer?->getId()): ?>
            <span class="logged-in">
                <?= $escaper->escapeHtml(__('Welcome, %1!', $customer->getName())) ?>
            </span>
        <?php else: ?>
            <span class="not-logged-in">
                <?= $escaper->escapeHtml($welcomeMessage) ?>
            </span>
            <?= $block->getBlockHtml('header.additional') ?>
        <?php endif; ?>
    </li>
<?php elseif ($block->getShowPart() == 'other'): ?>
    <?= $block->getChildHtml() ?>
<?php endif ?>
